# -*- coding: utf-8 -*-
"""DBSCAN-and-PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGnPoHjhsS8nmjEGZuw50y8e90ONVR_V
"""

import pandas as pd
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=500, noise=0.05, random_state=42)

df = pd.DataFrame(X, columns=["Feature1", "Feature2"])

print(df.head(10))
print("Shape:", df.shape)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

print(X_scaled[:5])

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

kmeans = KMeans(n_clusters=2, random_state=42)
df["kmeans_cluster"] = kmeans.fit_predict(X_scaled)

plt.figure(figsize=(6,5))
plt.scatter(df["Feature1"], df["Feature2"], c=df["kmeans_cluster"], cmap="viridis")
plt.title("K-Means Clustering")
plt.xlabel("Feature1")
plt.ylabel("Feature2")
plt.show()

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.3, min_samples=5)
df["dbscan_cluster"] = dbscan.fit_predict(X_scaled)

plt.figure(figsize=(6,5))
plt.scatter(df["Feature1"], df["Feature2"], c=df["dbscan_cluster"], cmap="rainbow")
plt.title("DBSCAN Clustering")
plt.xlabel("Feature1")
plt.ylabel("Feature2")
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

# KMeans Plot
plt.subplot(1,2,1)
plt.scatter(df["Feature1"], df["Feature2"],
            c=df["kmeans_cluster"], cmap="viridis")
plt.title("KMeans Clustering")
plt.xlabel("Feature1")
plt.ylabel("Feature2")

# DBSCAN Plot
plt.subplot(1,2,2)
plt.scatter(df["Feature1"], df["Feature2"],
            c=df["dbscan_cluster"], cmap="rainbow")
plt.title("DBSCAN Clustering")
plt.xlabel("Feature1")
plt.ylabel("Feature2")

plt.tight_layout()
plt.show()

results = []

for eps in [0.2, 0.3, 0.4, 0.5]:
    db = DBSCAN(eps=eps, min_samples=5)
    labels = db.fit_predict(X_scaled)

    clusters = len(set(labels)) - (1 if -1 in labels else 0)
    noise = list(labels).count(-1)

    results.append([eps, clusters, noise])

result_df = pd.DataFrame(results, columns=["eps", "No_of_Clusters", "Noise_Points"])

print(result_df)

from sklearn.datasets import make_blobs

X_blob, y_blob = make_blobs(
    n_samples=500,
    n_features=6,
    centers=4,
    cluster_std=1.5,
    random_state=42
)

scaler = StandardScaler()
X_blob_scaled = scaler.fit_transform(X_blob)

from sklearn.decomposition import PCA

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_blob_scaled)

pca_df = pd.DataFrame(X_pca, columns=["PC1", "PC2"])
pca_df["Cluster"] = y_blob

print("Explained Variance Ratio:")
print(pca.explained_variance_ratio_)

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA

iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

dbscan = DBSCAN(eps=0.8, min_samples=5)
labels = dbscan.fit_predict(X_scaled)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(6,5))
plt.scatter(X_pca[:,0], X_pca[:,1], c=labels, cmap="rainbow")
plt.title("DBSCAN + PCA on Iris Dataset")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()