# -*- coding: utf-8 -*-
"""Unsupervised Learning & Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c_NhmvFQBDvKUi7i8iozTMl5riZ9lBiZ
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

from google.colab import files
uploaded = files.upload()

import io
import pandas as pd

df = pd.read_csv(io.BytesIO(uploaded['iris (1).csv']))
X = df.iloc[:, [1, 2, 3, 4]].values

"""##Elbow Method

"""

wcss = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42, n_init=10)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

"""##Elbow Graph"""

plt.figure(figsize=(6,4))
plt.plot(range(1,11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("WCSS")
plt.grid(True)
plt.show()

"""##K-Means Clustering

"""

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df["Cluster"] = kmeans.fit_predict(X)

df.head()

"""##Visualize the Clusters"""

plt.figure(figsize=(6,4))
plt.scatter(df.iloc[:, 2], df.iloc[:, 3], c=df["Cluster"], cmap="viridis")
plt.xlabel("Petal Length")
plt.ylabel("Petal Width")
plt.title("K-Means Clustering on Iris Dataset")
plt.show()